In [1]:
# Slicing Arrays

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8]) # Slice elements from index 1 to index 5 from the following array:
print(arr[1:5])

[2 3 4 5]


In [4]:
"""
We pass slice instead of index like this: [start:end]
We can also define the step, like this: [start:end:step]
If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1
"""

"\nWe pass slice instead of index like this: [start:end]\nWe can also define the step, like this: [start:end:step]\nIf we don't pass start its considered 0\nIf we don't pass end its considered length of array in that dimension\nIf we don't pass step its considered 1\n"

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) # Slice elements from index 4 to the end of the array:
print(arr[4:])

[5 6 7]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) # Slice elements from the beginning to index 4 (not included):
print(arr[:4])

[1 2 3 4]


In [7]:
# Negative Slicing

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-4:-1])

[4 5 6]


In [10]:
# STEP

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8])
print(arr[0:7:3])

[1 4 7]


In [13]:
print(arr[1:8:3])

[2 5 8]


In [14]:
print(arr[::2]) # Return every other element from the entire array

[1 3 5 7]


In [15]:
# Slicing 2-D Arrays

In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) # Remember that second element has index 1

[7 8 9]


In [18]:
print(arr[0, 2:5]) # Remember that first element has index 0

[3 4 5]


In [19]:
print(arr[0:2, 2]) # From both elements, return index 2

[3 8]


In [22]:
print(arr[0:2, 3]) # From both elements, return index 3

[4 9]


In [23]:
print(arr[0:2, 1:4]) # This will return a 2-D array

[[2 3 4]
 [7 8 9]]
